# coding: utf-8

"""
    Number Operator

    This is a sample server python-flask.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Number Operator",
    author_email="prokhorov.va@phystech.edu",
    url="",
    keywords=["Swagger", "Number Operator"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is a sample server python-flask.  # noqa: E501
    """
)
