# coding: utf-8

"""
    Number Operator

    This is a sample server python-flask.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clear_api import ClearApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClearApi(unittest.TestCase):
    """ClearApi unit test stubs"""

    def setUp(self):
        self.api = ClearApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_results(self):
        """Test case for delete_results

        clear list of requests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
