# coding: utf-8

# flake8: noqa
"""
    Number Operator

    This is a sample server python-flask.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.nums import Nums
from swagger_client.models.results import Results
